#!/bin/bash

# Activar el entorno virtual
source venv/Scripts/activate

# Si no hay argumentos, ejecutar todas las pruebas
if [ $# -eq 0 ]; then
    python -m pytest -v --html=report.html
    exit 0
fi

# Si el primer argumento es --tags
if [ "$1" = "--tags" ]; then
    python -m pytest -v -m "$2" --html=report.html
    exit 0
fi

# Si es un archivo específico
python -m pytest -v "$1" --html=report.html 